AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Url-shortner-gnk-practice

  Sample SAM Template for Url-shortner-gnk-practice
Parameters:
  ProjectName:
    Type: String
    Default: url-shortener-gnk
  Environment:
    Type: String
    Default: Prod

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Runtime: nodejs20.x
    Architectures: 
      - arm64
    MemorySize: 256
    Timeout: 15
    Environment:
      Variables:
        NODE_OPTIONS: "--max-old-space-size=128"
        LOG_LEVEL: "info"
        TABLE_NAME: !Sub "${ProjectName}-${Environment}-urls"
    Tracing: Active

    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
Resources:
  UrlsTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: !Sub "${ProjectName}-${Environment}-urls"
      AttributeDefinitions:
        - AttributeName: shortId
          AttributeType: S
      KeySchema:
        - AttributeName: shortId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  ServerlessRestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Environment
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"

  GetShortUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: app.getShortUrlHandler  
      Events:
        PostShorten:
          Type: Api
          Properties:
            RestApiId: !Ref ServerlessRestApi
            Path: /get-url-shortener
            Method: post
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UrlsTable
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - app.ts       
  RedirectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: app.redirectHandler      
      Events:
        GetRedirect:
          Type: Api
          Properties:
            RestApiId: !Ref ServerlessRestApi
            Path: /short/{id+}
            Method: get
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UrlsTable
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - app.ts

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ApiUrl:
    Description: "GNK URL Shortener API"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/"
  TableName:
    Description: "DynamoDB Table"
    Value: !Ref UrlsTable